export enum ServiceEnum {
  // SWITCH-AND-SOCKET
  'SWITCH-BOX-INSTALLATION' = 10,
  'AC-SWITCHBOX-INSTALLATION' = 11,
  'SWITCHBOARD-INSTALLATION' = 12,
  'SMART-SWITCH-INSTALLTION' = 13,
  'SMART-APPLIANCE-CONTROLLER' = 14,
  'WIFI-SMART-SWITCH-INSTALLTION' = 15,
  'SWITCH-SOCKET-REPLACEMENT' = 16,
  'SWITCHBOARD-SWITCHBOX-REPAIR' = 17,

  //
}
