export enum ServiceEnum {
  // SWITCH-AND-SOCKET
  'SWITCH-BOX-INSTALLATION' = 10,
  'AC-SWITCHBOX-INSTALLATION' = 11,
  'SWITCHBOARD-INSTALLATION' = 12,
  'SMART-SWITCH-INSTALLTION' = 13,
  'SMART-APPLIANCE-CONTROLLER' = 14,
  'WIFI-SMART-SWITCH-INSTALLTION' = 15,
  'SWITCH-SOCKET-REPLACEMENT' = 16,
  'SWITCHBOARD-SWITCHBOX-REPAIR' = 17,

  //FAN
  'FAN-REPLACEMENT' = 3,
  'FAN-INSTALLATION' = 4,
  'FAN-UNINSTALLATION' = 8,
  'FAN-REGULATOR-REPAIR-REPLACEMENT' = 9,
  'FAN-REPAIR' = 18,

  //MCB-SUBMETER
  'SINGLE-POLE-MCB-INSTALLATION' = 19,
  'DOUBLE-POLE-MCB-INSTALLATION' = 20,
  'MCB-FUSE-REPLACEMENT' = 21,
  'SUBMETER-INSTALLATION' = 22,
  '3-PHASE-CHANGEOVER-SWITCH-INSTALLATION' = 23
}
